// Mocks generated by Mockito 5.3.2 from annotations
// in deardiary/test/widget_home_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;

import 'widget_home_page_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [JournalEntryDialogModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockJournalEntryDialogModel extends _i1.Mock
    implements _i2.JournalEntryDialogModel {
  MockJournalEntryDialogModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set journalEntryID(int? _journalEntryID) => super.noSuchMethod(
        Invocation.setter(
          #journalEntryID,
          _journalEntryID,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get ownerID => (super.noSuchMethod(
        Invocation.getter(#ownerID),
        returnValue: '',
      ) as String);
  @override
  set ownerID(String? _ownerID) => super.noSuchMethod(
        Invocation.setter(
          #ownerID,
          _ownerID,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get onlineID => (super.noSuchMethod(
        Invocation.getter(#onlineID),
        returnValue: '',
      ) as String);
  @override
  set onlineID(String? _onlineID) => super.noSuchMethod(
        Invocation.setter(
          #onlineID,
          _onlineID,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get journalEntryTitle => (super.noSuchMethod(
        Invocation.getter(#journalEntryTitle),
        returnValue: '',
      ) as String);
  @override
  set journalEntryTitle(String? _journalEntryTitle) => super.noSuchMethod(
        Invocation.setter(
          #journalEntryTitle,
          _journalEntryTitle,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get journalEntryContent => (super.noSuchMethod(
        Invocation.getter(#journalEntryContent),
        returnValue: '',
      ) as String);
  @override
  set journalEntryContent(String? _journalEntryContent) => super.noSuchMethod(
        Invocation.setter(
          #journalEntryContent,
          _journalEntryContent,
        ),
        returnValueForMissingStub: null,
      );
  @override
  DateTime get journalEntryCreationDate => (super.noSuchMethod(
        Invocation.getter(#journalEntryCreationDate),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.getter(#journalEntryCreationDate),
        ),
      ) as DateTime);
  @override
  set journalEntryCreationDate(DateTime? _journalEntryCreationDate) =>
      super.noSuchMethod(
        Invocation.setter(
          #journalEntryCreationDate,
          _journalEntryCreationDate,
        ),
        returnValueForMissingStub: null,
      );
  @override
  DateTime get journalEntryLastUpdate => (super.noSuchMethod(
        Invocation.getter(#journalEntryLastUpdate),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.getter(#journalEntryLastUpdate),
        ),
      ) as DateTime);
  @override
  set journalEntryLastUpdate(DateTime? _journalEntryLastUpdate) =>
      super.noSuchMethod(
        Invocation.setter(
          #journalEntryLastUpdate,
          _journalEntryLastUpdate,
        ),
        returnValueForMissingStub: null,
      );
}
